"""added new fields on Packages table

Revision ID: 34c65ea982f7
Revises: 053b2a134ce8
Create Date: 2023-07-23 20:21:28.135613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c65ea982f7'
down_revision = '053b2a134ce8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_tag',
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('package_id', 'tag')
    )
    op.create_table('package_version_dependency',
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('dependency', sa.String(), nullable=False),
    sa.Column('dependency_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dependency', 'dependency_version'], ['package_version.package_id', 'package_version.version'], ),
    sa.ForeignKeyConstraint(['dependency'], ['package.id'], ),
    sa.ForeignKeyConstraint(['dependency_version'], ['package_version.version'], ),
    sa.ForeignKeyConstraint(['package_id', 'version'], ['package_version.package_id', 'package_version.version'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['version'], ['package_version.version'], ),
    sa.PrimaryKeyConstraint('package_id', 'version', 'dependency', 'dependency_version')
    )
    op.add_column('package', sa.Column('description', sa.String(), nullable=True))
    op.add_column('package', sa.Column('meta', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'meta')
    op.drop_column('package', 'description')
    op.drop_table('package_version_dependency')
    op.drop_table('package_tag')
    # ### end Alembic commands ###
